version: 2.1
orbs:
  node: circleci/node@4.1.1
  aws-cli: circleci/aws-cli@1.4.0
workflows:
  deploy-dev:
    jobs:
      - deploy-dev:
          context: aws-repl-deploy
jobs:
    #
    # Dev
    #
    deploy-dev:
      docker:
        - image: cimg/node:14.15.5
      steps:
        - checkout
        - aws-cli/setup:
            profile-name: repl-deploy
        - run:
            name: Deploy dev
            command: |
              pushd lambda-runner
              npm install
              AWS_PROFILE=repl-deploy npm run deploy:dev
              popd
              pushd ui
              npm install
              npm run build
              netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN --site f9516a60-5190-4b42-b14b-9c0cc2eb8de5 --dir dist
