version: 2.1
orbs:
  node: circleci/node@4.1.1
  aws-cli: circleci/aws-cli@1.4.0
workflows:
  deploy-dev:
    jobs:
      - deploy-dev:
          context: aws-repl-deploy
jobs:
    #
    # Dev
    #
    deploy-dev:
      docker:
        - image: cimg/node:14.15.5
      steps:
        - checkout
        - aws-cli/setup:
            profile-name: repl-deploy
        - run:
            name: Deploy dev
            command: |
              pushd lambda-runner
              npm install
              AWS_PROFILE=repl-deploy npm run deploy:dev
              URLS=$(./node_modules/.bin/serverless info --verbose | grep ServiceEndpoint | sed s/ServiceEndpoint\.\*\:\ //g)
              popd
              pushd ui
              echo "UI_HTTP_BASE_URL=$(echo $URLS | awk -F " " '{ print $1 }')" >> .env
              echo "UI_WS_ENDPOINT=$(echo $URLS | awk -F " " '{ print $2 }')" >> .env
              echo "UI_BASE_DOMAIN=superrepl.com" >> .env
              yarn install
              yarn build
              yarn add netlify-cli
              ./node_modules/.bin/netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN --site f9516a60-5190-4b42-b14b-9c0cc2eb8de5 --dir dist
